version: "3"
services:
  web:
    image: antilamer/thing-tracker:initial
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 175M
      restart_policy:
        condition: on-failure
    ports:
    - "8443:8443"
    networks:
    - webnet
networks:
  webnet: