version: "3.7"
services:
  web:
    image: antilamer/thing-tracker:ssl3
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://34.77.197.231:5432/thing_tracker
    volumes:
    - /etc/letsencrypt/live/thing-tracker.ga:/etc/letsencrypt/live/thing-tracker.ga
    - /opt/logs/thing-tracker:/opt/logs/thing-tracker
    deploy:
      replicas: 1
#      max-replicas-per-node: 1
      resources:
        limits:
          cpus: "0.9"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
    - "443:8443"
    networks:
    - webnet
  rabbitmq-stomp:
    image: antilamer/rabbitmq-stomp:3.7
    deploy:
      placement:
        constraints:
        - node.role == manager
    ports:
    - "5672:5672"
    - "15672:15672"
    - "61613:61613"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - webnet
  postgres:
    image: antilamer/postgres:tracker1.1
    deploy:
      placement:
        constraints:
        - node.role == manager
    volumes:
    - /my_dbdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=thing_tracker
    - POSTGRES_USER=antilamer
    - POSTGRES_PASSWORD=antilamer
    ports:
    - "5432:5432"
networks:
  webnet: