version: "3.7"
services:
  web:
    image: antilamer/thing-tracker:ssl2
    volumes:
    - /etc/letsencrypt/live/thing-tracker.ga:/etc/letsencrypt/live/thing-tracker.ga
    - /opt/logs/thing-tracker:/opt/logs/thing-tracker
    deploy:
      replicas: 1
#      max-replicas-per-node: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
    - "443:8443"
    - "80:80"
    networks:
    - webnet
  rabbitmq-stomp:
    image: antilamer/rabbitmq-stomp:3.7
    deploy:
      placement:
        constraints:
        - node.role == manager
    ports:
    - "5672:5672"
    - "15672:15672"
    - "61613:61613"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - webnet
networks:
  webnet: