pipeline {
    tools {
        jdk 'jdk 8u221'
        maven 'maven 3.6.1'
        nodejs 'nodejs 10.16.1'
    }
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Install node modules and build frontend') {
            steps {
                sh 'npm install --prefix ./front'
                sh 'npm run build:prod --prefix ./front'
            }
        }
        stage('Build .war') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
